# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "echovox" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "echovox_password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "echovox_development" } %>

test:
  <<: *default
  database: echovox_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "echovox_production" } %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
